<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Helper for complete HTML documents generated by AI/packages.
 */
final class HUB_Tibox_Landing_Document
{
    public static function render(string $html, int $landing_id, string $base_url = ''): void
    {
        $html = self::replace_variables($html, $landing_id);

        if ($base_url !== '' && stripos($html, '<base ') === false) {
            $base = '<base href="' . esc_url($base_url) . '">';
            $html = self::inject_into_head($html, $base, true);
        }

        ob_start();
        wp_head();
        $head = (string) ob_get_clean();

        ob_start();
        if (function_exists('wp_body_open')) {
            wp_body_open();
        } else {
            do_action('wp_body_open'); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound -- WordPress core hook, fired as a fallback on very old versions.
        }
        $body_open = (string) ob_get_clean();

        ob_start();
        wp_footer();
        $footer = (string) ob_get_clean();

        $html = self::inject_into_head($html, $head, false);
        $html = self::inject_after_body_open($html, $body_open);
        $html = self::inject_before_body_close($html, $footer);

        status_header(200);
        header('Content-Type: text/html; charset=' . get_bloginfo('charset'));
        header('X-Content-Type-Options: nosniff');
        header('Referrer-Policy: strict-origin-when-cross-origin');

        echo $html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- trusted administrator-authored HTML.
        exit;
    }

    public static function replace_variables(string $html, int $landing_id): string
    {
        return HUB_Tibox_Variables::replace($html, $landing_id, ['form_target' => $landing_id]);
    }

    private static function inject_into_head(string $html, string $content, bool $prefer_start): string
    {
        if ($content === '') {
            return $html;
        }

        if ($prefer_start && preg_match('/<head(?:\s[^>]*)?>/i', $html)) {
            return preg_replace('/<head(?:\s[^>]*)?>/i', '$0' . $content, $html, 1) ?? $html;
        }

        if (stripos($html, '</head>') !== false) {
            return preg_replace('/<\/head>/i', $content . '</head>', $html, 1) ?? $html;
        }

        return $content . $html;
    }

    private static function inject_after_body_open(string $html, string $content): string
    {
        if ($content === '') {
            return $html;
        }
        if (preg_match('/<body(?:\s[^>]*)?>/i', $html)) {
            return preg_replace('/<body(?:\s[^>]*)?>/i', '$0' . $content, $html, 1) ?? $html;
        }
        return $html;
    }

    private static function inject_before_body_close(string $html, string $content): string
    {
        if ($content === '') {
            return $html;
        }
        if (stripos($html, '</body>') !== false) {
            return preg_replace('/<\/body>/i', $content . '</body>', $html, 1) ?? $html;
        }
        return $html . $content;
    }
}
