<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * The single variable registry for every HUB design.
 *
 * Header/Footer components and Landings each carried their own resolver, and
 * they had already drifted apart: `{{MENU_PRIMARY}}` only worked in components,
 * `{{HUB_FORM}}` only in landings. A design generated by an AI could therefore
 * be correct for one destination and print raw braces on the other. This class
 * is the only place where a `{{VARIABLE}}` is defined or resolved.
 */
final class HUB_Tibox_Variables
{
    public const CONTRACT_VERSION = '1.0';

    /**
     * Definition of every variable exposed to designs.
     *
     * @return array<string,array{label:string,group:string,html:bool}>
     */
    public static function registry(): array
    {
        $registry = [
            'SITE_URL' => ['label' => 'URL del sitio, sin barra final', 'group' => 'sitio', 'html' => false],
            'HOME_URL' => ['label' => 'URL de la portada, con barra final', 'group' => 'sitio', 'html' => false],
            'SITE_NAME' => ['label' => 'Nombre del sitio', 'group' => 'sitio', 'html' => false],
            'SITE_DESCRIPTION' => ['label' => 'Descripción del sitio', 'group' => 'sitio', 'html' => false],
            'CURRENT_YEAR' => ['label' => 'Año actual', 'group' => 'sitio', 'html' => false],
            'CUSTOM_LOGO' => ['label' => 'Logo del sitio como HTML', 'group' => 'sitio', 'html' => true],
            'CUSTOM_LOGO_URL' => ['label' => 'URL del archivo del logo', 'group' => 'sitio', 'html' => false],
            'PRIVACY_URL' => ['label' => 'URL del aviso de privacidad', 'group' => 'sitio', 'html' => false],

            'MENU_PRIMARY' => ['label' => 'Menú de la ubicación primary', 'group' => 'navegacion', 'html' => true],
            'MENU_FOOTER' => ['label' => 'Menú de la ubicación footer', 'group' => 'navegacion', 'html' => true],
            'MENU_SECONDARY' => ['label' => 'Menú de la ubicación secondary', 'group' => 'navegacion', 'html' => true],

            'PAGE_ID' => ['label' => 'ID del contenido en pantalla', 'group' => 'contexto', 'html' => false],
            'PAGE_TITLE' => ['label' => 'Título del contenido en pantalla', 'group' => 'contexto', 'html' => false],
            'PAGE_URL' => ['label' => 'URL del contenido en pantalla', 'group' => 'contexto', 'html' => false],
            'PAGE_EXCERPT' => ['label' => 'Extracto del contenido en pantalla', 'group' => 'contexto', 'html' => false],
            'FEATURED_IMAGE' => ['label' => 'URL de la imagen destacada', 'group' => 'contexto', 'html' => false],

            'DESIGN_ID' => ['label' => 'ID del diseño HUB', 'group' => 'diseno', 'html' => false],
            'DESIGN_TITLE' => ['label' => 'Título del diseño HUB', 'group' => 'diseno', 'html' => false],
            'DESIGN_URL' => ['label' => 'Permalink del diseño HUB', 'group' => 'diseno', 'html' => false],
            'DESIGN_SCOPE' => ['label' => 'Clase de aislamiento CSS del diseño', 'group' => 'diseno', 'html' => false],

            'HUB_FORM' => ['label' => 'Formulario HUB estándar', 'group' => 'formulario', 'html' => true],
            'FORM_ENDPOINT' => ['label' => 'Endpoint REST del formulario', 'group' => 'formulario', 'html' => false],

            // Historical aliases from the Landings module. Kept so designs made
            // before the unification keep resolving.
            'LANDING_URL' => ['label' => 'Alias de DESIGN_URL', 'group' => 'compatibilidad', 'html' => false],
            'LANDING_TITLE' => ['label' => 'Alias de DESIGN_TITLE', 'group' => 'compatibilidad', 'html' => false],
        ];

        return (array) apply_filters('constructor_hub_variable_registry', $registry);
    }

    /** @return string[] */
    public static function names(): array
    {
        return array_keys(self::registry());
    }

    /**
     * Resolve every registered variable for one context.
     *
     * @param array<string,mixed> $context
     * @return array<string,string>
     */
    public static function values(int $design_id = 0, array $context = []): array
    {
        $queried_id = (int) ($context['page_id'] ?? get_queried_object_id());
        $logo_id = (int) get_theme_mod('custom_logo', 0);
        $thumbnail = $queried_id > 0 ? (string) get_the_post_thumbnail_url($queried_id, 'full') : '';

        $values = [
            'SITE_URL' => untrailingslashit(esc_url(home_url('/'))),
            'HOME_URL' => esc_url(home_url('/')),
            'SITE_NAME' => esc_html(get_bloginfo('name')),
            'SITE_DESCRIPTION' => esc_html(get_bloginfo('description')),
            'CURRENT_YEAR' => esc_html(wp_date('Y')),
            'CUSTOM_LOGO' => has_custom_logo() ? (string) get_custom_logo() : esc_html(get_bloginfo('name')),
            'CUSTOM_LOGO_URL' => $logo_id > 0 ? esc_url((string) wp_get_attachment_image_url($logo_id, 'full')) : '',
            'PRIVACY_URL' => esc_url((string) apply_filters(
                'constructor_hub_privacy_url',
                home_url('/aviso-de-privacidad/'),
                $design_id
            )),

            'MENU_PRIMARY' => self::menu('primary'),
            'MENU_FOOTER' => self::menu('footer'),
            'MENU_SECONDARY' => self::menu('secondary'),

            'PAGE_ID' => (string) $queried_id,
            'PAGE_TITLE' => $queried_id > 0 ? esc_html(get_the_title($queried_id)) : esc_html(get_bloginfo('name')),
            'PAGE_URL' => $queried_id > 0 ? esc_url((string) get_permalink($queried_id)) : esc_url(home_url('/')),
            'PAGE_EXCERPT' => $queried_id > 0 ? esc_html(get_the_excerpt($queried_id)) : '',
            'FEATURED_IMAGE' => esc_url($thumbnail),

            'DESIGN_ID' => (string) $design_id,
            'DESIGN_TITLE' => $design_id > 0 ? esc_html(get_the_title($design_id)) : '',
            'DESIGN_URL' => $design_id > 0 ? esc_url((string) get_permalink($design_id)) : '',
            'DESIGN_SCOPE' => sanitize_html_class((string) ($context['scope'] ?? '')),

            'FORM_ENDPOINT' => esc_url(rest_url('constructor-hub/v1/landing-submit')),
            'HUB_FORM' => '',
        ];

        if (class_exists('HUB_Tibox_Landing_Forms')) {
            $form_target = (int) ($context['form_target'] ?? ($design_id > 0 ? $design_id : $queried_id));
            $values['HUB_FORM'] = HUB_Tibox_Landing_Forms::instance()->render_default_form($form_target);
        }

        $values['LANDING_URL'] = $values['DESIGN_URL'] !== '' ? $values['DESIGN_URL'] : $values['PAGE_URL'];
        $values['LANDING_TITLE'] = $values['DESIGN_TITLE'] !== '' ? $values['DESIGN_TITLE'] : $values['PAGE_TITLE'];

        /**
         * Site adapters extend the contract here. A value added by an adapter
         * must also be declared through `constructor_hub_variable_registry` so
         * the import validator and the admin reference stay truthful.
         */
        return (array) apply_filters('constructor_hub_variable_values', $values, $design_id, $context);
    }

    /**
     * @param array<string,mixed> $context
     */
    public static function replace(string $content, int $design_id = 0, array $context = []): string
    {
        if ($content === '' || !str_contains($content, '{{')) {
            return $content;
        }

        $map = [];
        foreach (self::values($design_id, $context) as $name => $value) {
            $map['{{' . $name . '}}'] = (string) $value;
        }

        return strtr($content, $map);
    }

    /**
     * Variables used by a design that this site cannot resolve.
     *
     * Used by the package importer so an AI gets an actionable error instead of
     * literal braces rendered on a live page.
     *
     * @return string[]
     */
    public static function unknown_in(string $content): array
    {
        if (!preg_match_all('/\{\{\s*([A-Z0-9_]+)\s*\}\}/', $content, $matches)) {
            return [];
        }

        $known = self::names();
        $unknown = [];
        foreach ($matches[1] as $name) {
            if (!in_array($name, $known, true)) {
                $unknown[] = $name;
            }
        }

        return array_values(array_unique($unknown));
    }

    private static function menu(string $location): string
    {
        if (!has_nav_menu($location)) {
            return '';
        }

        return (string) wp_nav_menu([
            'theme_location' => $location,
            'container' => '',
            'echo' => false,
            'fallback_cb' => false,
        ]);
    }
}
